### ISSUE TITLE
Add MutationObserver to also work with dynamic changes

### ISSUE THREAD

**Issue by scorpion421** [Cside/return-amazon-5-stars-and-number-of-reviews#19] opened 2023-09-01 21:53 UTC
I altered the code to include MutationObserver, because as soon as I clicked a checkmark (like Prime), I had to refresh the page to make the script working again.

Here is the changed code :)

[AMZ_5_Stars_Rating_Mod.txt](https://github.com/Cside/return-amazon-5-stars-and-number-of-reviews/files/12501670/AMZ_5_Stars_Rating_Mod.txt)

Thanks for the script!

**Comment by Cside** [comment] 2023-09-01 23:55
@scorpion421 
Thanks for the patch.

The browser extension version is monitoring the URL changes [in this code](https://github.com/Cside/return-amazon-5-stars-and-number-of-reviews/blob/main/src/background/main.ts#L7-L28
), so when you click on the check mark, the script will run again.
In the [UserScript version](https://greasyfork.org/ja/scripts/474149) (like TamperMonkey or GreaseMonkey), the script will not run again at the moment.

Are you an UserScript user?

**Comment by Cside** [comment] 2023-09-02 00:10
There are two improvements to your code:

1. The CSS :has() pseudo selector cannot be used in Firefox, so you need to use a function like [querySelectorAllWithHas()](https://gist.github.com/Cside/6ba29d5c6ede1348518311150ce52152).
2. Re-running the code every time the DOM of document.body changes is too much wasteful processing, so it might be better to narrow the scope of the DOM.

**Comment by Cside** [comment] 2023-09-02 05:27
@scorpion421 
I've released [version 0.0.2 of the userscript](https://greasyfork.org/scripts/474149) and it now also works with dynamic changes.

Thanks for your great suggestion.
I'll close this Issue now that the issue is resolved.

**Closed as completed by Cside** 2023-09-02 05:27 UTC

**Comment by scorpion421** [comment] 2023-09-03 00:11
Don't want to grave dig (had no time to reply): You can enable the pseudo selector in Firefox:
about:config > layout.css.has-selector.enabled to true. Forgot to mention it.
